title: Here is a place you will know about Suraj 
author: SURAJ
email: vsuraj1999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Software developer with great knowledge of Networking technologies.
# social links
twitter_username: vsuraj1999 # DO NOT include the @ character, or else the build will fail!
github_username:  vsuraj1999 # DO NOT include the @ character, or else the build will fail!
linkedin-username: https://www.linkedin.com/in/suraj-kumar-verma-a0056a17b/
instagram: suraj.verma__
show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
